<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2>Carrito por pedir</h2>

    <?php
    $cart = $_SESSION['user']->getCart();

    echo "Carrito empezado el " . $cart->getOrderDate() . "<br>";

    foreach ($cart->getOrderLines() as $orderLine) { //

        echo "Producto: " . $orderLine->getProduct()->getName() . ", Cantidad: " . $orderLine->getQuantity() . "<br>";
    }

    ?>
    <br>
    <a href="index.php?c=order&confirm">Confirmar Pedido</a>
</body>

</html>