<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php

    echo "<h2>" . $thread->getName() . "</h2>";

    foreach ($thread->getMessages() as $message) {

        echo "<p>" . $message->getAuthor()->getUsername() . ": " . $message->getText() . "<br>(" . $message->getDatetime() . ")</p>";
    }

    ?>
</body>

</html>